development:
  hosts: ["127.0.0.1:9200"]
  bootstrap: true
  index: sprangular_demo_development

test:
  hosts: ["127.0.0.1:9200"]
  bootstrap: true
  index: sprangular_demo_test

production:
  hosts: ["https://zle92jzm:mbetoj8kr8qsa62o@oak-1530123.us-east-1.bonsai.io"]
  bootstrap: true
  index: sprangular_demo
